### ISSUE TITLE
Change of Shopping Cart Output

### ISSUE THREAD

**Issue by dbltoe** [lat9/multiship#36]
When subtotals, tax, shipping, and totals are shown on the checkout, they are out of sequence and alignment.
Suggest swapping lines 79-80 and 96=97 of includes/templates/template_default/templates/tpl_modules_multiship.php so that lineTitle is first and totalBox is second in each instance.
Then, rename includes/templates/YOUR_TEMPLATE/css/checkout_multiship.css to includes/templates/YOUR_TEMPLATE/css/stylesheet_zmultiship.css and add the following lines:
.totalBox {width:5%;float:right;}
.lineTitle {width:85%;float:left;}
This allows the monetary data to be shown correctly in all views and responsive.  It also insures that any multiship-related styles are, in fact, committed.
Docs under installation will need to be changed to reflect the name change (6-26)
I have made the changes on the test site. 
John

**Comment by lat9** [comment]
That's something to do with your site's configuration.  I've used a clone of `responsive_classic` for development and the totals line up properly; see the [storefront documentation](https://github.com/lat9/multiship/blob/master/pages/multiship_storefront_changes.md) that I've created &mdash; there's no alignment issue there.

**Comment by dbltoe** [comment]
You are correct.  In looking deeper I find some css for another site.
